$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($env:TAURI_UPDATER_PUBLIC_KEY)) {
    throw 'Set the TAURI_UPDATER_PUBLIC_KEY repository variable to the contents of your Tauri .pub file.'
}
if ([string]::IsNullOrWhiteSpace($env:TAURI_SIGNING_PRIVATE_KEY)) {
    throw 'Set the TAURI_SIGNING_PRIVATE_KEY repository secret before publishing signed updates.'
}

$publicKey = $env:TAURI_UPDATER_PUBLIC_KEY.Trim()
try {
    $decodedKey = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($publicKey))
    $keyLines = $decodedKey.Trim() -split '\r?\n'
    if ($keyLines.Count -ne 2 -or -not $keyLines[0].StartsWith('untrusted comment:') -or
        [Convert]::FromBase64String($keyLines[1]).Length -ne 42) {
        throw 'Invalid public key format.'
    }
} catch {
    throw 'TAURI_UPDATER_PUBLIC_KEY must contain the complete base64 public key generated by tauri signer generate.'
}

# Merge with the full build configuration so local thin builds need no signing key.
$config = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot '../src-tauri/tauri.windows.full.conf.json') | ConvertFrom-Json
$config.bundle | Add-Member -NotePropertyName createUpdaterArtifacts -NotePropertyValue $true
$config | Add-Member -NotePropertyName plugins -NotePropertyValue @{ updater = @{ pubkey = $publicKey } }
$destination = Join-Path $PSScriptRoot '../src-tauri/tauri.updater.release.conf.json'
$config | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $destination -Encoding utf8
Write-Output 'Prepared signed updater configuration.'
