$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($env:TAURI_UPDATER_PUBLIC_KEY)) {
    throw 'Set the TAURI_UPDATER_PUBLIC_KEY environment variable to the contents of your Tauri .pub file.'
}
if ([string]::IsNullOrWhiteSpace($env:TAURI_SIGNING_PRIVATE_KEY)) {
    throw 'Set the TAURI_SIGNING_PRIVATE_KEY environment variable to your private key path or contents before publishing signed updates.'
}

$publicKey = $env:TAURI_UPDATER_PUBLIC_KEY.Trim()
try {
    $decodedKey = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($publicKey))
    $keyLines = $decodedKey.Trim() -split '\r?\n'
    if ($keyLines.Count -ne 2 -or -not $keyLines[0].StartsWith('untrusted comment:') -or
        [Convert]::FromBase64String($keyLines[1]).Length -ne 42) {
        throw 'Invalid public key format.'
    }
} catch {
    throw 'TAURI_UPDATER_PUBLIC_KEY must contain the complete base64 public key generated by tauri signer generate.'
}

# Signing is shared by both editions; only the full configuration adds resources.
$config = @{
    '$schema' = 'https://schema.tauri.app/config/2'
    bundle = @{ createUpdaterArtifacts = $true }
    plugins = @{ updater = @{ pubkey = $publicKey } }
}
$destination = Join-Path $PSScriptRoot '../src-tauri/tauri.updater.release.conf.json'
$config | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $destination -Encoding utf8
Write-Output 'Prepared signed updater configuration.'
