import assert from "node:assert/strict"
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import os from "node:os"
import path from "node:path"
import test from "node:test"

import { execute } from "./release-local.mjs"
import {
  compareVersions,
  releaseWizard,
  suggestedVersion,
  versionEdits,
} from "./release-wizard.mjs"

function fixture(t, overrides = {}) {
  const directory = mkdtempSync(path.join(os.tmpdir(), "arcrecall-wizard-"))
  const root = path.join(directory, "work")
  const remote = path.join(directory, "remote.git")
  mkdirSync(root)
  t.after(() => rmSync(directory, { recursive: true, force: true }))
  const write = (file, contents) => {
    const destination = path.join(root, file)
    mkdirSync(path.dirname(destination), { recursive: true })
    writeFileSync(destination, contents)
  }
  const git = (args) => execute("git", args, { cwd: root, capture: true })
  git(["init", "--initial-branch=main"])
  git(["config", "user.name", "Release Test"])
  git(["config", "user.email", "release-test@example.invalid"])
  git(["config", "commit.gpgsign", "false"])
  git(["config", "tag.gpgsign", "false"])
  git(["config", "core.hooksPath", path.join(directory, "no-hooks")])
  write("package.json", '{"version":"0.1.1","other":"unchanged"}\n')
  write("src-tauri/tauri.conf.json", '{"version":"0.1.1"}\n')
  write(
    "Cargo.toml",
    '[workspace]\nmembers = ["src-tauri", "crates/core"]\nresolver = "2"\n'
  )
  write(
    "src-tauri/Cargo.toml",
    '[package]\nname = "arc-recall-desktop"\nversion = "0.1.1"\nedition = "2024"\n'
  )
  write("src-tauri/src/lib.rs", "pub fn hello() {}\n")
  write(
    "crates/core/Cargo.toml",
    '[package]\nname = "arc-recall-core"\nversion = "0.1.0"\nedition = "2024"\n'
  )
  write("crates/core/src/lib.rs", "pub fn core() {}\n")
  write(
    "Cargo.lock",
    '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "arc-recall-core"\nversion = "0.1.0"\n\n[[package]]\nname = "arc-recall-desktop"\nversion = "0.1.1"\n'
  )
  git(["add", "."])
  git(["commit", "-m", "Initial fixture"])
  git(["init", "--bare", remote])
  git(["remote", "add", "origin", remote])
  git(["push", "origin", "main"])
  const initial = git(["rev-parse", "HEAD"])
  const calls = []
  const answers = overrides.answers ?? [
    "修复导入失败",
    "改善压缩速度",
    ".",
    "y",
  ]
  let published = 0
  const releaseOptions = []
  const messages = []
  let confirmHook = overrides.confirmHook
  const command = (program, args, options) => {
    calls.push({ program, args })
    overrides.beforeCommand?.(program, args, { git, write })
    if (overrides.fail?.(program, args)) throw new Error("simulated failure")
    if (program === "gh") {
      if (args[1] === "user") return overrides.login ?? "ZhongYanZhiShi"
      return JSON.stringify([overrides.draft ? [overrides.draft] : []])
    }
    if (program === "git") {
      if (args[0] === "remote" && args[1] === "get-url")
        return "git@github.com:ZhongYanZhiShi/ArcRecall.git"
      return execute(program, args, { ...options, capture: true })
    }
    if (program === "cargo")
      return execute(program, args, { ...options, capture: true })
    return ""
  }
  return {
    root,
    git,
    write,
    calls,
    initial,
    releaseOptions,
    messages,
    get published() {
      return published
    },
    run: (options = { tag: "v0.1.2" }) =>
      releaseWizard(options, {
        root,
        execute: command,
        platform: "win32",
        arch: "x64",
        env: {
          TAURI_UPDATER_PUBLIC_KEY: "fixture-public",
          TAURI_SIGNING_PRIVATE_KEY: "fixture-private",
        },
        log: (message) => messages.push(message),
        ask: async (question) => {
          if (question.startsWith("开始执行") && confirmHook) {
            confirmHook({ git, write })
            confirmHook = undefined
          }
          assert.ok(answers.length, `Unexpected prompt: ${question}`)
          return answers.shift()
        },
        release: (options) => {
          const { tag } = options
          releaseOptions.push(options)
          published++
          const head = git(["rev-parse", "HEAD"])
          assert.equal(git(["status", "--porcelain"]), "")
          assert.equal(git(["rev-parse", `refs/tags/${tag}^{commit}`]), head)
          assert.ok(
            git(["ls-remote", "origin", `refs/tags/${tag}`]).startsWith(head)
          )
          assert.ok(
            git(["ls-remote", "origin", "refs/heads/main"]).startsWith(head)
          )
          if (overrides.buildFailure) throw new Error("build failed")
        },
      }),
  }
}

test("默认递增补丁版本，预发布默认转同版本正式版", () => {
  assert.equal(suggestedVersion("0.1.1"), "0.1.2")
  assert.equal(suggestedVersion("1.0.0-beta.2"), "1.0.0")
  const ordered = [
    "0.9.9",
    "1.0.0-alpha",
    "1.0.0-alpha.2",
    "1.0.0-alpha.10",
    "1.0.0-beta",
    "1.0.0-beta.1",
    "1.0.0",
    "1.0.1",
    "2.0.0",
  ]
  for (let i = 1; i < ordered.length; i++) {
    assert.equal(compareVersions(ordered[i - 1], ordered[i]), -1)
    assert.equal(compareVersions(ordered[i], ordered[i - 1]), 1)
  }
  assert.equal(compareVersions("1.0.0-beta.1", "1.0.0-beta.1"), 0)
})

test("回车采用建议版本，提交并推送 main 和标签，默认交给草稿发布器", async (t) => {
  const f = fixture(t, {
    answers: ["", "修复导入失败", "改善压缩速度", ".", "y"],
  })
  await f.run({})
  assert.equal(f.published, 1)
  assert.equal(f.releaseOptions[0].publish, false)
  assert.ok(f.messages.some((message) => message.includes("（草稿）")))
  assert.equal(
    JSON.parse(readFileSync(path.join(f.root, "package.json"))).version,
    "0.1.2"
  )
  assert.match(
    readFileSync(path.join(f.root, "Cargo.lock"), "utf8"),
    /name = "arc-recall-core"\nversion = "0.1.0"/
  )
  assert.match(
    readFileSync(path.join(f.root, "Cargo.lock"), "utf8"),
    /name = "arc-recall-desktop"\nversion = "0.1.2"/
  )
  assert.equal(
    readFileSync(path.join(f.root, ".github/release-notes/v0.1.2.md"), "utf8"),
    "- 修复导入失败\n- 改善压缩速度\n"
  )
  assert.equal(f.git(["rev-list", "--count", "HEAD"]), "2")
  assert.deepEqual(
    f.calls.find(({ program, args }) => program === "git" && args[0] === "push")
      .args,
    [
      "push",
      "--atomic",
      "origin",
      "HEAD:refs/heads/main",
      "refs/tags/v0.1.2:refs/tags/v0.1.2",
    ]
  )
})

test("显式指定版本和 publish 才传递自动发布", async (t) => {
  const f = fixture(t)
  await f.run({ tag: "v0.1.2", publish: true })
  assert.deepEqual(f.releaseOptions, [{ tag: "v0.1.2", publish: true }])
  assert.ok(
    f.messages.some((message) => message.includes("上传校验后自动发布"))
  )
})

test("取消不修改文件、创建提交或标签", async (t) => {
  const f = fixture(t, { answers: ["修复问题", ".", "n"] })
  await f.run()
  assert.equal(f.git(["status", "--porcelain"]), "")
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
  assert.equal(f.git(["tag", "--list"]), "")
  assert.equal(f.published, 0)
})

test("未提交源码和错误分支在版本写入前停止", async (t) => {
  const f = fixture(t)
  f.write("unrelated.txt", "user work")
  await assert.rejects(f.run(), /未提交改动/)
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
  f.git(["add", "unrelated.txt"])
  f.git(["commit", "-m", "User work"])
  f.git(["switch", "-c", "feature"])
  await assert.rejects(f.run(), /main 分支/)
  assert.equal(f.published, 0)
})

test("非维护者和已发布版本不会创建提交或标签", async (t) => {
  for (const overrides of [
    { login: "someone" },
    {
      draft: {
        tag_name: "v0.1.2",
        draft: false,
        prerelease: false,
        assets: [],
      },
    },
  ]) {
    const f = fixture(t, overrides)
    await assert.rejects(f.run(), /登录|已正式发布/)
    assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
    assert.equal(f.git(["tag", "--list"]), "")
  }
})

test("拒绝降低版本和重新使用旧标签", async (t) => {
  const f = fixture(t)
  await assert.rejects(f.run({ tag: "v0.1.0" }), /必须高于/)
  f.git(["tag", "v0.1.2"])
  await assert.rejects(f.run(), /已存在/)
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
})

test("确认期间新增源码改动不会被发布提交包含", async (t) => {
  const f = fixture(t, {
    confirmHook: ({ write }) => write("important.txt", "new user work"),
  })
  await assert.rejects(f.run(), /未提交改动/)
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
  assert.equal(
    readFileSync(path.join(f.root, "important.txt"), "utf8"),
    "new user work"
  )
})

test("推送失败保留本地提交和标签，重试不重复升版或提交", async (t) => {
  let failPush = true
  const f = fixture(t, {
    answers: ["修复问题", ".", "y", "y"],
    fail: (program, args) =>
      failPush && program === "git" && args[0] === "push",
  })
  await assert.rejects(f.run(), /simulated failure/)
  const commit = f.git(["rev-parse", "HEAD"])
  assert.notEqual(commit, f.initial)
  assert.equal(f.published, 0)
  failPush = false
  await f.run()
  assert.equal(f.git(["rev-parse", "HEAD"]), commit)
  assert.equal(f.git(["rev-list", "--count", "HEAD"]), "2")
  assert.equal(f.published, 1)
})

test("打包失败后保留可重试的版本，不撤销远端标签", async (t) => {
  const f = fixture(t, { buildFailure: true })
  await assert.rejects(f.run(), /build failed/)
  assert.ok(f.git(["ls-remote", "origin", "refs/tags/v0.1.2"]))
  assert.equal(f.git(["status", "--porcelain"]), "")
})

test("恢复发布拒绝移动指向其他提交的标签", async (t) => {
  const f = fixture(t, { answers: ["修复问题", ".", "y"] })
  await f.run()
  f.write("later.txt", "later work")
  f.git(["add", "later.txt"])
  f.git(["commit", "-m", "Later work"])
  await assert.rejects(f.run(), /拒绝移动/)
  assert.equal(f.published, 1)
})

test("版本不一致时不生成部分文件修改", (t) => {
  const f = fixture(t)
  f.write("src-tauri/tauri.conf.json", '{"version":"0.0.1"}')
  assert.throws(() => versionEdits(f.root, "0.1.2"), /不一致/)
  assert.equal(
    JSON.parse(readFileSync(path.join(f.root, "package.json"))).version,
    "0.1.1"
  )
})

test("远端 main 有新提交时不创建版本提交或标签", async (t) => {
  const f = fixture(t)
  f.write("remote-change.txt", "remote change")
  f.git(["add", "remote-change.txt"])
  f.git(["commit", "-m", "Remote change"])
  f.git(["push", "origin", "main"])
  // Move only this disposable fixture branch back to simulate a stale checkout.
  f.git(["switch", "--detach", f.initial])
  f.git(["branch", "--force", "main", f.initial])
  f.git(["switch", "main"])
  await assert.rejects(f.run(), /远端最新提交/)
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
  assert.equal(f.git(["tag", "--list"]), "")
  assert.equal(f.git(["status", "--porcelain"]), "")
})

test("检查期间出现被工作区掩盖的无关暂存修改也会停止提交", async (t) => {
  const f = fixture(t, {
    beforeCommand: (program, args, { git, write }) => {
      if (program !== "cargo" || args[0] !== "metadata") return
      write("src-tauri/src/lib.rs", "pub fn user_edit() {}\n")
      git(["add", "src-tauri/src/lib.rs"])
      write("src-tauri/src/lib.rs", "pub fn hello() {}\n")
    },
  })
  await assert.rejects(f.run(), /发布文件以外/)
  assert.equal(f.git(["rev-parse", "HEAD"]), f.initial)
  assert.match(f.git(["diff", "--cached"]), /user_edit/)
  assert.equal(f.published, 0)
})

test("重试时保留远端附注标签，缺少本地标签则取回原标签", async (t) => {
  const f = fixture(t, { answers: ["修复问题", ".", "y", "y"] })
  // Prepare the version without reaching the first push.
  for (const [file, content] of versionEdits(f.root, "0.1.2"))
    f.write(file, content)
  f.write(
    ".github/release-notes/v0.1.2.md",
    "# ArcRecall v0.1.2\n\n- 修复问题\n"
  )
  f.git(["add", "."])
  f.git(["commit", "-m", "Prepare version"])
  f.git(["tag", "-a", "v0.1.2", "-m", "Annotated release"])
  const tagObject = f.git(["rev-parse", "refs/tags/v0.1.2"])
  f.git(["push", "origin", "main", "v0.1.2"])
  f.git(["tag", "-d", "v0.1.2"])
  // Existing notes skip the notes prompts.
  await releaseWizard(
    { tag: "v0.1.2" },
    {
      root: f.root,
      platform: "win32",
      arch: "x64",
      env: {
        TAURI_UPDATER_PUBLIC_KEY: "fixture",
        TAURI_SIGNING_PRIVATE_KEY: "fixture",
      },
      ask: async () => "y",
      log: () => {},
      execute: (program, args, options) => {
        if (program === "gh")
          return args[1] === "user" ? "ZhongYanZhiShi" : "[[]]"
        if (program === "git" && args[0] === "remote")
          return "git@github.com:ZhongYanZhiShi/ArcRecall.git"
        if (program === "git")
          return execute(program, args, { ...options, capture: true })
        return ""
      },
      release: () => {},
    }
  )
  assert.equal(f.git(["rev-parse", "refs/tags/v0.1.2"]), tagObject)
})
